// Generated by hand from Firebase Console → Project Settings
// Project: omee-ganatra-productions
//
// To add iOS/Android: Firebase Console → Project Settings → Add App
// then replace the placeholder values below.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQmjHXB4iQ_viSRi1w9GXle9swoA3Ha1Q',
    authDomain: 'omee-ganatra-productions.firebaseapp.com',
    projectId: 'omee-ganatra-productions',
    storageBucket: 'omee-ganatra-productions.firebasestorage.app',
    messagingSenderId: '1094303353895',
    appId: '1:1094303353895:web:079462d336f33c62461202',
    measurementId: 'G-N4QD6QZ3CX',
  );

  // Replace after: Firebase Console → Add Android app (com.omeeganatra.ogp)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQmjHXB4iQ_viSRi1w9GXle9swoA3Ha1Q',
    authDomain: 'omee-ganatra-productions.firebaseapp.com',
    projectId: 'omee-ganatra-productions',
    storageBucket: 'omee-ganatra-productions.firebasestorage.app',
    messagingSenderId: '1094303353895',
    appId: '1:1094303353895:android:REPLACE_WITH_ANDROID_APP_ID',
  );

  // Replace after: Firebase Console → Add iOS app (com.omeeganatra.ogp)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQmjHXB4iQ_viSRi1w9GXle9swoA3Ha1Q',
    authDomain: 'omee-ganatra-productions.firebaseapp.com',
    projectId: 'omee-ganatra-productions',
    storageBucket: 'omee-ganatra-productions.firebasestorage.app',
    messagingSenderId: '1094303353895',
    appId: '1:1094303353895:ios:REPLACE_WITH_IOS_APP_ID',
    iosBundleId: 'com.omeeganatra.ogp',
  );
}
